basePath: /api/v1
definitions:
  enums.AppError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: Name is require
        type: string
      status_code:
        example: INVALID_QUERY_PARAM
        type: string
    type: object
  enums.UserStatus:
    enum:
    - 0
    - 1
    - 2
    type: integer
    x-enum-comments:
      UserStatusActive: "1"
      UserStatusInactive: "0"
      UserStatusLocked: "2"
    x-enum-varnames:
    - UserStatusInactive
    - UserStatusActive
    - UserStatusLocked
  itemDTO.CreateItemRequest:
    properties:
      description:
        type: string
      image:
        type: string
      name:
        type: string
    required:
    - name
    type: object
  itemDTO.CreateItemResponse:
    properties:
      item:
        $ref: '#/definitions/itemDTO.ItemDTO'
    type: object
  itemDTO.CreateItemResponseWrapper:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/itemDTO.CreateItemResponse'
      message:
        type: string
    type: object
  itemDTO.DeleteItemResponseWrapper:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  itemDTO.GetItemByIDResponse:
    properties:
      item:
        $ref: '#/definitions/itemDTO.ItemDTO'
    type: object
  itemDTO.GetItemByIDResponseWrapper:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/itemDTO.GetItemByIDResponse'
      message:
        type: string
    type: object
  itemDTO.GetItemResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/itemDTO.ItemDTO'
        type: array
      totalPage:
        type: integer
    type: object
  itemDTO.GetItemResponseWrapper:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/itemDTO.GetItemResponse'
      message:
        type: string
    type: object
  itemDTO.ItemDTO:
    properties:
      description:
        type: string
      id:
        type: integer
      image:
        type: string
      name:
        type: string
    type: object
  itemDTO.UpdateItemRequest:
    properties:
      description:
        type: string
      id:
        type: integer
      image:
        type: string
      name:
        type: string
    required:
    - id
    type: object
  itemDTO.UpdateItemResponse:
    properties:
      item:
        $ref: '#/definitions/itemDTO.ItemDTO'
    type: object
  itemDTO.UpdateItemResponseWrapper:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/itemDTO.UpdateItemResponse'
      message:
        type: string
    type: object
  userDTO.CreateUserRequest:
    properties:
      address:
        type: string
      email:
        type: string
      fullName:
        type: string
      goodPoint:
        type: integer
      password:
        minLength: 8
        type: string
      phoneNumber:
        type: string
      status:
        allOf:
        - $ref: '#/definitions/enums.UserStatus'
        enum:
        - 0
        - 1
        - 2
    required:
    - email
    - fullName
    - password
    type: object
  userDTO.CreateUserResponse:
    properties:
      user:
        $ref: '#/definitions/userDTO.UserDTO'
    type: object
  userDTO.CreateUserResponseWrapper:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/userDTO.CreateUserResponse'
      message:
        type: string
    type: object
  userDTO.DeleteUserResponseWrapper:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  userDTO.GetUserByIDResponse:
    properties:
      user:
        $ref: '#/definitions/userDTO.UserDTO'
    type: object
  userDTO.GetUserByIDResponseWrapper:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/userDTO.GetUserByIDResponse'
      message:
        type: string
    type: object
  userDTO.GetUserResponse:
    properties:
      totalPage:
        type: integer
      users:
        items:
          $ref: '#/definitions/userDTO.UserDTO'
        type: array
    type: object
  userDTO.GetUserResponseWrapper:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/userDTO.GetUserResponse'
      message:
        type: string
    type: object
  userDTO.UpdateUserRequest:
    properties:
      address:
        type: string
      avatar:
        type: string
      email:
        type: string
      fullName:
        type: string
      goodPoint:
        type: integer
      id:
        type: integer
      password:
        minLength: 8
        type: string
      phoneNumber:
        type: string
      status:
        allOf:
        - $ref: '#/definitions/enums.UserStatus'
        enum:
        - 0
        - 1
        - 2
    type: object
  userDTO.UpdateUserResponseWrapper:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  userDTO.UserDTO:
    properties:
      address:
        type: string
      avatar:
        type: string
      email:
        type: string
      fullName:
        type: string
      goodPoint:
        type: integer
      id:
        type: integer
      phoneNumber:
        type: string
      status:
        type: integer
    type: object
host: 34.142.168.171:8000
info:
  contact:
    email: trannguyentrungkien1006@gmail.com
    name: Kin
  description: Đây là tài liệu Swagger cho hệ thống.
  license:
    name: Apache 2.0
  termsOfService: http://swagger.io/terms/
  title: API DATN 2025
  version: "1.0"
paths:
  /items:
    get:
      consumes:
      - application/json
      description: API bao gồm cả lọc, phân trang và sắp xếp
      parameters:
      - description: Current page
        example: 1
        in: query
        minimum: 1
        name: page
        type: integer
      - description: Number record per page
        example: 10
        in: query
        minimum: 1
        name: limit
        type: integer
      - description: 'Sort column (vd: name)'
        example: name
        in: query
        name: sort
        type: string
      - description: 'Sort type: ASC hoặc DESC'
        example: ASC
        in: query
        name: order
        type: string
      - description: Filter by name or description
        example: '"{\"name\":\"item1\"}"'
        in: query
        name: filter
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/itemDTO.GetItemResponseWrapper'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/enums.AppError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/enums.AppError'
      summary: Get items
      tags:
      - items
    post:
      consumes:
      - application/json
      description: API thêm item mới
      parameters:
      - description: Create item info
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/itemDTO.CreateItemRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Created item successfully
          schema:
            $ref: '#/definitions/itemDTO.CreateItemResponseWrapper'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/enums.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/enums.AppError'
      summary: Create new item
      tags:
      - items
    put:
      consumes:
      - application/json
      description: API cập nhật item
      parameters:
      - description: Update item info
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/itemDTO.UpdateItemRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Updated item successfully
          schema:
            $ref: '#/definitions/itemDTO.UpdateItemResponseWrapper'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/enums.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/enums.AppError'
      summary: Update item
      tags:
      - items
  /items/{itemID}:
    delete:
      consumes:
      - application/json
      description: API xóa item theo ID
      parameters:
      - description: ID item
        in: path
        name: itemID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Deleted item successfully
          schema:
            $ref: '#/definitions/itemDTO.DeleteItemResponseWrapper'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/enums.AppError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/enums.AppError'
      summary: Delete item
      tags:
      - items
    get:
      consumes:
      - application/json
      description: API lấy thông tin item theo ID
      parameters:
      - description: ID item
        in: path
        name: itemID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/itemDTO.GetItemByIDResponseWrapper'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/enums.AppError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/enums.AppError'
      summary: Get item by ID
      tags:
      - items
  /users:
    get:
      consumes:
      - application/json
      description: API bao gồm cả lọc, phân trang và sắp xếp
      parameters:
      - description: Current page
        example: 1
        in: query
        minimum: 1
        name: page
        type: integer
      - description: Number record of page
        example: 10
        in: query
        minimum: 1
        name: limit
        type: integer
      - description: 'Sort column (vd: name, email)'
        example: name
        in: query
        name: sort
        type: string
      - description: 'Sort type: ASC hoặc DESC'
        example: ASC
        in: query
        name: order
        type: string
      - description: Filter by name or email
        example: '"{\"name\":\"John\", \"email\":\"john@gmail.com\"}"'
        in: query
        name: filter
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/userDTO.GetUserResponseWrapper'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/enums.AppError'
      summary: Get users
      tags:
      - users
    post:
      consumes:
      - application/json
      description: API thêm người dùng
      parameters:
      - description: Create user info
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/userDTO.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created user successfully
          schema:
            $ref: '#/definitions/userDTO.CreateUserResponseWrapper'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/enums.AppError'
      summary: Create user
      tags:
      - users
    put:
      consumes:
      - application/json
      description: API cập nhật người dùng
      parameters:
      - description: Update user info
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/userDTO.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Updated user successfully
          schema:
            $ref: '#/definitions/userDTO.UpdateUserResponseWrapper'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/enums.AppError'
      summary: Update user
      tags:
      - users
  /users/{userID}:
    delete:
      consumes:
      - application/json
      description: API delete user by id
      parameters:
      - description: ID user
        in: path
        name: userID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/userDTO.DeleteUserResponseWrapper'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/enums.AppError'
      summary: Delete user
      tags:
      - users
    get:
      consumes:
      - application/json
      description: API get user by id
      parameters:
      - description: ID user
        in: path
        name: userID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/userDTO.GetUserByIDResponseWrapper'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/enums.AppError'
      summary: Get user by ID
      tags:
      - users
swagger: "2.0"
